name: Build and deploy React app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: fb-clone
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "18.x"

# Controls when the workflow will run
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Copy build files
        run: |
          mkdir -p ${{ runner.workspace }}/build
          cp -r build/* ${{ runner.workspace }}/build

      - name: Archive build files
        run: |
          zip -r build.zip build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: www
          path: build.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: www
          path: build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build.zip
