# This is a basic workflow to help you get started with Actions

name: Build and deploy React app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: fb-clone
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "18.x"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      # Runs a single command using the runners shell
      - name: variables check
        run: |
          echo Hello, world!
          echo ${{ env.NODE_VERSION }}
          echo ${{ env.AZURE_WEBAPP_NAME }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present -- --passWithNoTests

      # Zips the artifact for deployment
      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH}}/build
          zip -r ../release.zip *
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: fb-clone-artifact
          path: release.zip

  deploy:
    if: github.repository == 'main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: fb-clone-artifact

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure WebApp"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
